---
  CinderVolumes.create_and_update_volume:
    -
      args:
        update_volume_kwargs:
           description: "desc_updated"
        create_volume_kwargs: {}
        size: 1
      runner:
        type: "constant"
        times: 3
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
      sla:
        failure_rate:
          max: 0
