---
  CinderVolumeTypes.create_and_get_volume_type:
    -
      args:
        description: "rally tests creating types"
      runner:
        type: "constant"
        times: 5
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2
      sla:
        failure_rate:
          max: 0
