  CinderVolumeTypes.create_and_list_encryption_type:
    -
      args:
        provider: "LuksEncryptor"
        cipher: "aes-xts-plain64"
        key_size: 512
        control_location: "front-end"
      runner:
        type: "constant"
        times: 4
        concurrency: 1
      context:
        users:
          tenants: 2
          users_per_tenant: 2
        volume_types: [
          "test_type1",
          "test_type2",
          "test_type3",
          "test_type4"
        ]
      sla:
        failure_rate:
          max: 0
