---
  NovaServers.boot_and_bounce_server:
    -
      args:
        flavor_id: 1
        image_id: "3fa4482f-677a-4488-adaf-c48befac5e5a"
        actions:
          -
            hard_reboot: 1
          -
            soft_reboot: 1
          -
            stop_start: 1
          -
            rescue_unrescue: 1
      runner:
        type: "constant"
        times: 10
        active_users: 2
      context:
        users:
          tenants: 3
          users_per_tenant: 2
