---
  SenlinClusters.create_and_delete_cluster:
    -
      args:
        desired_capacity: 3
        min_size: 0
        max_size: 5
      runner:
        type: "constant"
        times: 3
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        profiles:
          type: os.nova.server
          version: "1.0"
          properties:
            name: cirros_server
            flavor: 1
            image: "cirros-0.3.4-x86_64-uec"
            networks:
              - network: private
