{% set flavor_name = flavor_name or "m1.tiny" %}
---
  VMTasks.boot_runcommand_delete:
    -
      args:
        flavor:
            name: "{{flavor_name}}"
        image:
            name: "^cirros.*uec$"
        volume_args:
            size: 2
        fixed_network: "private"
        floating_network: "public"
        use_floating_ip: true
        force_delete: false
        command:
            interpreter: "/bin/sh"
            script_file: "samples/tasks/support/instance_dd_test.sh"
        username: "cirros"
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 3
          users_per_tenant: 2
