---
  HeatStacks.create_suspend_resume_delete_stack:
    -
      args:
        template_path: "templates/random_strings.yaml.template"
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 3
          users_per_tenant: 2