---
  HeatStacks.create_update_delete_stack:
    -
      args:
        template_path: "templates/autoscaling_policy.yaml.template"
        updated_template_path: "templates/updated_autoscaling_policy_inplace.yaml.template"
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 3
