---
  HeatStacks.create_and_delete_stack:
    -
      args:
        template_path: "samples/tasks/scenarios/heat/templates/resource-group-server-with-volume.yaml.template"
        parameters:
           num_instances: 2
        files: ["samples/tasks/scenarios/heat/templates/server-with-volume.yaml.template"]
      runner:
        type: "constant"
        times: 3
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 3
