---
  HeatStacks.create_stack_and_list_output:
    -
      args:
        template_path: "samples/tasks/scenarios/heat/templates/resource-group-with-outputs.yaml.template"
      runner:
        type: "constant"
        times: 5
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2

  HeatStacks.create_stack_and_list_output_via_API:
    -
      args:
        template_path: "samples/tasks/scenarios/heat/templates/resource-group-with-outputs.yaml.template"
      runner:
        type: "constant"
        times: 5
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2