{% set flavor_name = flavor_name or "m1.tiny" %}
---
NovaServers.boot_server_from_volume_and_live_migrate:
- args:
    flavor:
      name: "{{flavor_name}}"
    image:
      name: "^cirros.*uec$"
    block_migration: false
    volume_size: 10
    force_delete: false
  runner:
    type: constant
    times: 10
    concurrency: 2
  context:
    users:
      tenants: 1
      users_per_tenant: 1
