{% set flavor_name = flavor_name or "m1.tiny" %}
---
  NovaServers.boot_and_live_migrate_server:
  - args:
      flavor:
        name: "{{flavor_name}}"
      image:
        name: "^cirros.*-disk$"
      block_migration: false
    runner:
      type: "constant"
      times: 10
      concurrency: 2
    context:
      users:
        tenants: 1
        users_per_tenant: 1
    sla:
      failure_rate:
        max: 0
