{% set flavor_name = flavor_name or "m1.tiny" %}
{% set volume_type = volume_type or "" %}
---
  NovaServers.boot_server_from_volume:
    -
      args:
        flavor:
            name: "{{flavor_name}}"
        image:
            name: "^cirros.*-disk$"
        volume_size: 10
        volume_type: "{{volume_type}}"
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 3
          users_per_tenant: 2
      sla:
        failure_rate:
          max: 0
