{% set flavor_name = flavor_name or "m1.tiny" %}
---
  NovaServers.boot_server_associate_and_dissociate_floating_ip:
    -
      args:
        flavor:
            name: "{{flavor_name}}"
        image:
            name: "^cirros.*-disk$"
      runner:
        type: "constant"
        times: 5
        concurrency: 2
      context:
        users:
          tenants: 3
          users_per_tenant: 2
        network: {}
      sla:
        failure_rate:
          max: 0
    -
      args:
        flavor:
            name: "{{flavor_name}}"
        image:
            name: "^cirros.*-disk$"
        create_floating_ip_args:
            ext_network: "ext_network_name"
      runner:
        type: "constant"
        times: 5
        concurrency: 2
      context:
        users:
          tenants: 3
          users_per_tenant: 2
        network: {}
      sla:
        failure_rate:
          max: 0

