---
  NovaServers.boot_and_list_server:
    -
      args:
        flavor:
            name: "m1.nano"
        image:
            name: "^cirros.*uec$"
        detailed: True
      runner:
        type: "constant"
        times: 1
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1

