{% set flavor_name = flavor_name or "m1.tiny" %}
---
  NovaServers.boot_and_rebuild_server:
  -
    args:
      flavor:
        name: "{{flavor_name}}"
      from_image:
        name: "^cirros.*-disk$"
      to_image:
        name: "^cirros.*-disk$"
    runner:
      type: "constant"
      times: 5
      concurrency: 2
    context:
      users:
        tenants: 1
        users_per_tenant: 1
    sla:
      failure_rate:
        max: 0
