{% set flavor_name = flavor_name or "m1.tiny" %}
{% set image_name = "^(cirros.*-disk|TestVM)$" %}
---
  NovaServers.boot_server_attach_volume_and_list_attachments:
    -
      args:
        flavor:
            name: "{{flavor_name}}"
        image:
            name: "{{image_name}}"
        volume_size: 1
        volume_num: 2
        boot_server_kwargs: {}
        create_volume_kwargs: {}
      runner:
        type: "constant"
        times: 5
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2
      sla:
        failure_rate:
          max: 0
