  NovaServerGroups.create_and_list_server_groups:
    -
      args:
        policies: ["affinity"]
        all_projects: false
      runner:
        type: "constant"
        times: 4
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2
      sla:
        failure_rate:
          max: 0
