{% set flavor_name = flavor_name or "m1.tiny" %}
---
  NovaServers.resize_shutoff_server:
    -
      args:
        flavor:
            name: "{{flavor_name}}"
        image:
            name: "^cirros.*-disk$"
        to_flavor:
            name: "m1.small"
        confirm: true
        force_delete: false
      runner:
        type: "constant"
        times: 5
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2
      sla:
        failure_rate:
          max: 0
