{% set flavor_name = flavor_name or "m1.tiny" %}
---
  NovaServers.resize_server:
    -
      args:
        flavor:
            name: "{{flavor_name}}"
        image:
            name: "^cirros.*uec$"
        to_flavor:
            name: "m1.small"
        confirm: true
        force_delete: false
      runner:
        type: "constant"
        times: 10
        concurrency: 5
      context:
        users:
          tenants: 1
          users_per_tenant: 1
