---
  NeutronNetworks.create_and_list_subnets:
    -
      args:
        network_create_args: {}
        subnet_create_args: {}
        subnet_cidr_start: "1.1.0.0/30"
        subnets_per_network: 2
      runner:
        type: "constant"
        times: 10
        concurrency: 5
      context:
        network: {}
        users:
          tenants: 2
          users_per_tenant: 3
        quotas:
          neutron:
            network: -1
            subnet: -1
