---
  NeutronSecurityGroup.create_and_list_security_group_rules:
    -
      args:
        security_group_args: {}
        security_group_rule_args: {}
      runner:
        type: "constant"
        times: 20
        concurrency: 10
      context:
        users:
          tenants: 3
          users_per_tenant: 3
        quotas:
          neutron:
            security_group: -1
      sla:
        failure_rate:
          max: 0
