---
  NeutronNetworks.create_and_list_networks:
    -
      args:
        network_create_args: {}
      runner:
        type: "constant"
        times: 100
        concurrency: 10
      context:
        users:
          tenants: 3
          users_per_tenant: 3
        quotas:
          neutron:
            network: -1
      sla:
        failure_rate:
          max: 0
    -
      args:
        network_create_args:
          provider:network_type: "vxlan"
      runner:
        type: "constant"
        times: 100
        concurrency: 10
      context:
        users:
          tenants: 3
          users_per_tenant: 3
        quotas:
          neutron:
            network: -1
        roles:
          - "admin"
      sla:
        failure_rate:
          max: 0
